name: neko-popup ci

on:
  push:
    tags:
      - v*

permissions:
  contents: write
  id-token: write

jobs:
  build:
    name: Build & publish package
    runs-on: ubuntu-latest

    steps:
      - name: Get the repository
        uses: actions/checkout@v4
      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm i
      - name: Run tests
        run: npm run test
      - name: Build package
        run: npm run build
      - name: Publish package to the NPM
        run: npm publish
      
  release:
    name: Create github release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --generate-notes
      