name: neko-popup CI

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest

    steps:
      - name: Get the repository
        uses: actions/checkout@v4
      - name: Setup nodejs
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm i

  release:
    name: Create github release
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --generate-notes